# Generated by Django 3.2.4 on 2021-07-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('icu', '0005_auto_20210703_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputs', models.JSONField()),
                ('output', models.FloatField()),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added At')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icu.patient')),
            ],
            options={
                'verbose_name': 'Model Prediction',
                'verbose_name_plural': 'Model Predictions',
            },
        ),
        migrations.AddIndex(
            model_name='modelprediction',
            index=models.Index(fields=['added_at'], name='predictors__added_a_fce28c_idx'),
        ),
    ]
