# Generated by Django 3.2.4 on 2021-07-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelprediction',
            name='inference_type',
            field=models.CharField(choices=[('sepsis', 'Sepsis'), ('mi', 'Myocardial Infarction (MI)'), ('vancomycin', 'Vancomycin'), ('aki', 'Acute Kidney Injury (AKI)'), ('mortality', 'Mortality')], default='sepsis', max_length=50, verbose_name='Inference Type'),
            preserve_default=False,
        ),
    ]
