# Generated by Django 3.2.4 on 2021-07-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0002_alter_chartevent_valuenum'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartevent',
            options={'verbose_name': 'ICU Chart Event', 'verbose_name_plural': 'ICU Chart Events'},
        ),
        migrations.AlterField(
            model_name='chartevent',
            name='value',
            field=models.CharField(blank=True, help_text='Contains the value measured for the concept identified by the ITEMID.', max_length=255, null=True, verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='chartevent',
            name='valueuom',
            field=models.CharField(blank=True, help_text='The unit of measurement for the value, if appropriate.', max_length=255, null=True, verbose_name='unit of measurement'),
        ),
    ]
