# Generated by Django 3.2.4 on 2021-07-03 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0003_auto_20210703_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartevent',
            name='icuevent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icu.icuevent', verbose_name='ICU Event'),
        ),
        migrations.AlterField(
            model_name='chartevent',
            name='icustay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icu.icustay', verbose_name='ICU Stay'),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='lab_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icu.labitem', verbose_name='Laboratory Item'),
        ),
    ]
