# Generated by Django 3.2.4 on 2021-07-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icu', '0004_auto_20210703_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appuser',
            options={},
        ),
        migrations.AlterField(
            model_name='appuser',
            name='contact_no',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='chartevent',
            name='charttime',
            field=models.DateTimeField(help_text='Records the time at which an observation was made, and is usually the closest proxy to the time the data was actually measured.', verbose_name='Chart Time'),
        ),
        migrations.AlterField(
            model_name='chartevent',
            name='storetime',
            field=models.DateTimeField(help_text='Records the time at which an observation was manually input or manually validated by a member of the clinical staff.', verbose_name='Store Time'),
        ),
        migrations.AlterField(
            model_name='labevent',
            name='labevent_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Laboratory Event ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact_no',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Contact Number'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['national_id'], name='icu_appuser_nationa_5aa6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='appuser',
            index=models.Index(fields=['worker_id'], name='icu_appuser_worker__8dcdfc_idx'),
        ),
    ]
